### ISSUE TITLE
Bug Fixes

### ISSUE THREAD

**Issue by xuemeihan** [xuemeihan/angularjs-la#1]
**Bug Fix to launch website**
Please fix all errors , and set up dev env fully.

**Comment by xuemeihan** [comment]
Please handle rejections from server response in PredicionModel Service. 

This will take only 1 or 2 hr to fix.

https://stackoverflow.com/questions/21455045/angularjs-http-cors-and-http-authentication
https://coderwall.com/p/lza07a/cors-with-angularjs

**Comment by siraj1044** [comment]
Issue fixed.
